config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#index"
  get 'find_points', to: 'home#search_points'
  get 'find_points_historic', to: 'home#search_points_historic'
  get 'insert_node', to: 'home#insert_node'
  get 'find_paths', to: 'home#search_ways'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if params[:search]
      sql = "SELECT p.name, ST_AsGeoJSON(ST_Transform(p.#{params[:search][:type]}, 4326)) FROM planet_osm_point p
      WHERE p.name
      LIMIT 100"
      @results = ActiveRecord::Base.connection.execute sql

    else
      @results = []
    end

    respond_to do |format|
      format.json {render json: @results}
      format.html
    end
  end

  def search_points
    if params[:search_coord]

      filter_string = ""

      if params[:search_coord][:type] == "All"
        filter_string = ""
      elsif params[:search_coord][:type] == "Unknown"
        filter_string += "AND coalesce(p.name, '') = ''"
      else
        filter_string += "AND coalesce(p.name, '') != ''"
      end

      sql = "SELECT p.name, ST_AsGeoJSON(ST_Transform(p.way, 4326)) FROM planet_osm_point  p
           WHERE ST_Contains(ST_MakePolygon(ST_GeomFromText('LINESTRING(#{params[:search_coord][:min_x]} #{params[:search_coord][:min_y]},
                                                                        #{params[:search_coord][:max_x]} #{params[:search_coord][:min_y]},
                                                                        #{params[:search_coord][:max_x]} #{params[:search_coord][:max_y]},
                                                                        #{params[:search_coord][:min_x]} #{params[:search_coord][:max_y]},
                                                                        #{params[:search_coord][:min_x]} #{params[:search_coord][:min_y]})', 4326)), ST_Transform(p.way, 4326))
           #{filter_string} LIMIT 1000"
      @results = ActiveRecord::Base.connection.execute sql

    else
      @results = []
    end

    respond_to do |format|
      format.json {render json: @results}
      format.html
    end
  end

  def insert_node
    if params[:insert_node_form]

      sql = "INSERT INTO planet_osm_point (osm_id, name, historic, way) VALUES
        (CAST( (SELECT Max(p.osm_id) FROM planet_osm_point p) AS BIGINT) + 1, '#{params[:insert_node_form][:name]}',
                                                                              '#{params[:insert_node_form][:type]}',
                                              ST_Transform(ST_GeomFromText('POINT(#{params[:insert_node_form][:x]} #{params[:insert_node_form][:y]})', 4326), 900913))
      RETURNING osm_id"

      id = ActiveRecord::Base.connection.execute sql

      sql2 = "SELECT p.name, ST_AsGeoJSON(ST_Transform(p.way, 4326)) FROM planet_osm_point p
      WHERE p.osm_id=#{id[0]['osm_id']} LIMIT 1"

      @results = ActiveRecord::Base.connection.execute sql2
    else
      @results = []
    end


    respond_to do |format|
      format.json {render json: @results}
      format.html
    end
  end

  def search_points_historic
    if params[:search_coord_historic]

      filter_string = ""

      if params[:search_coord_historic][:type] == "castle"
        filter_string += "AND coalesce(p.historic, '') = 'castle'"

      elsif params[:search_coord_historic][:type] == "battlefield"
        filter_string += "AND coalesce(p.historic, '') = 'battlefield'"

      elsif params[:search_coord_historic][:type] == "unknown"
        filter_string += "AND coalesce(p.historic, '') != 'castle'
                          AND coalesce(p.historic, '') != 'battlefield'
                          AND coalesce(p.historic, '') != 'memorial'
                          AND coalesce(p.historic, '') != 'monument'
                          AND coalesce(p.historic, '') != 'archaeological_site'
                          AND coalesce(p.historic, '') != 'bondary_stone'"

      elsif params[:search_coord_historic][:type] == "memorial"
        filter_string += "AND coalesce(p.historic, '') = 'memorial'"

      elsif params[:search_coord_historic][:type] == "monument"
        filter_string += "AND coalesce(p.historic, '') = 'monument'"

      elsif params[:search_coord_historic][:type] == "archaeological_site"
        filter_string += "AND coalesce(p.historic, '') = 'archaeological_site'"

      elsif params[:search_coord_historic][:type] == 'bondary_stone'
        filter_string += "AND coalesce(p.historic, '') = 'bondary_stone'"

      end

      sql = "SELECT p.name, p.historic, ST_AsGeoJSON(ST_Transform(p.way, 4326)) FROM planet_osm_point  p
           WHERE ST_Contains(ST_MakePolygon(ST_GeomFromText('LINESTRING(#{params[:search_coord_historic][:min_x]} #{params[:search_coord_historic][:min_y]},
                                                                        #{params[:search_coord_historic][:max_x]} #{params[:search_coord_historic][:min_y]},
                                                                        #{params[:search_coord_historic][:max_x]} #{params[:search_coord_historic][:max_y]},
                                                                        #{params[:search_coord_historic][:min_x]} #{params[:search_coord_historic][:max_y]},
                                                                        #{params[:search_coord_historic][:min_x]} #{params[:search_coord_historic][:min_y]})', 4326)), ST_Transform(p.way, 4326))
           #{filter_string} LIMIT 1000"
      @results = ActiveRecord::Base.connection.execute sql

    else
      @results = []
    end

    respond_to do |format|
      format.json {render json: @results}
      format.html
    end
  end

  def search_ways
    if params[:find_paths_form]

      sql = "SELECT p.name, ST_AsGeoJSON(ST_Transform(p.way, 4326)) FROM planet_osm_line  p
           WHERE ST_Contains(ST_MakePolygon(ST_GeomFromText('LINESTRING(#{params[:find_paths_form][:min_x]} #{params[:find_paths_form][:min_y]},
                                                                        #{params[:find_paths_form][:max_x]} #{params[:find_paths_form][:min_y]},
                                                                        #{params[:find_paths_form][:max_x]} #{params[:find_paths_form][:max_y]},
                                                                        #{params[:find_paths_form][:min_x]} #{params[:find_paths_form][:max_y]},
                                                                        #{params[:find_paths_form][:min_x]} #{params[:find_paths_form][:min_y]})', 4326)), ST_Transform(p.way, 4326))
           LIMIT 1000"
      @results = ActiveRecord::Base.connection.execute sql

    else
      @results = []
    end

    respond_to do |format|
      format.json {render json: @results}
      format.html
    end
  end

  def find_nodes_page

  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<% content_for :body do %>

    <div id='navigation' class="nav nav-static-top navbar-ight bg-faded">
      <ul class="nav navbar-nav">
        <li class="nav-item active"><a id="home_page">Home</a></li>
        <li class="nav-item"><a id="find_nodes_page">Find nodes</a></li>
        <li class="nav-item"><a id="find_historic_page">Find signseeing</a></li>
        <li class="nav-item"><a id="append_nodes_page">Append nodes</a></li>
        <li class="nav-item"><a id="road_page">Road between points</a></li>
        <li class="nav-item"><a id="find_roads_page">View Bratislava roads</a></li>

      </ul>
    </div>

    <div class="jumbotron text-center">

        <h1> Sightseeing map </h1>
        <p> Help turists find sightseeings</p>

    </div>


    <div class="container">

        <div id="find_nodes" name="find_nodes_name">
          <div class="col-sm-4">
              <h2> Find nodes </h2>

              <p>Data in database from (min_x:16.95, max_x: 17.32, min_y:48, 06, max: 48.2) (LIMITED to 1000 objects) </p>
              <%= simple_form_for :search_coord, url: find_points_url, method: :get do |f| %>
                  <%= f.input :min_x, label: 'Min X:', :input_html => { :value => "17.1" }%>
                  <%= f.input :max_x, label: 'Max X:', :input_html => { :value => "17.11" }  %>
                  <%= f.input :min_y, label: 'Min Y:', :input_html => { :value => "48.12" } %>
                  <%= f.input :max_y, label: 'Max Y:', :input_html => { :value => "48.13" }  %>
                  <%= f.input :type , collection: ["All", "Unknown", "With description"], include_blank: false %>
              <% end %>
          </div>

          <div class="col-sm-4">
              <h4>Legend</h4>
              <p>Green: with description</p>
              <p>Grey: unknow type</p>

              <button id="search_coord">Search in collection</button>
          </div>
        </div>

        <div id="find_historic" >

          <div class="col-sm-4">
            <h2> Find sightseeing(historic) </h2>

            <p>Find sigtseeing (min_x:16.95, max_x: 17.32, min_y:48, 06, max: 48.2) (LIMITED to 1000 objects) </p>
            <%= simple_form_for :search_coord_historic, url: find_points_historic_url, method: :get do |f| %>
                <%= f.input :min_x, label: 'Min X:', :input_html => { :value => "16" }%>
                <%= f.input :max_x, label: 'Max X:', :input_html => { :value => "18" }  %>
                <%= f.input :min_y, label: 'Min Y:', :input_html => { :value => "48" } %>
                <%= f.input :max_y, label: 'Max Y:', :input_html => { :value => "49" }  %>
                <%= f.input :type , collection: ["all", "unknown", "castle", "battlefield", "memorial", "monument", "archaeological_site", "bondary_stone"], include_blank: false %>
            <% end %>
            </div>
          <div class="col-sm-4">
            <h4>Legend</h4>
            <p>Grey: unknown type</p>
            <p>Black: castle </p>
            <p>Red: battlefield </p>
            <p>Green: memorial </p>
            <p>Monument: yellow </p>
            <p>Archeologic site: orange </p>
            <p>Blue: bundary stone </p>

            <button id="search_coord_historic">Search in collection</button>
            </div>
          </div>
        <div id="append_nodes" class="col-sm-4">
            <h2> Apppend node </h2>
            <p>Append node in database </p>
            <%= simple_form_for :insert_node_form, url: insert_node_url, method: :get do |f| %>
                <%= f.input :name, label: 'Name:', :input_html => { :value => "Petrzalsky hrad" }%>
                <%= f.input :x, label: 'X:', :input_html => { :value => "17.1" } %>
                <%= f.input :y, label: 'Y:', :input_html => { :value => "17.1" }%>
                <%= f.input :type , collection: ["unknown", "castle", "battlefield", "memorial", "monument", "archaeological_site", "bondary_stone"], include_blank: false %>
            <% end %>

            <button id="insert_node_button">Insert in database</button>
          </div>
        <div id="road" class="col-sm-4">

            <h2> Road between two points</h2>

            <p>Road between points </p>

          <form action="demo_form.asp">
            Point 1x: <input type="text" id="road_x1" value="17.1"><br>
            Point 1y: <input type="text" id="road_y1" value="48.1"><br>
            Point 2x: <input type="text" id="road_x2" value="17.12"><br>
            Point 2y: <input type="text" id="road_y2" value="48.12"><br>
          </form>

          <button id="find_path_button">Find paths</button>

        </div>

        <div id="find_roads" class="col-sm-4">
          <%= simple_form_for :find_paths_form, url: find_paths_url, method: :get do |f| %>
              <%= f.input :min_x, label: 'Min X:', :input_html => { :value => "17.1" }%>
              <%= f.input :max_x, label: 'Max X:', :input_html => { :value => "17.14" }  %>
              <%= f.input :min_y, label: 'Min Y:', :input_html => { :value => "48.13" }%>
              <%= f.input :max_y, label: 'Max Y:', :input_html => { :value => "48.15" } %>
          <% end %>

          <button id="find_paths_button">Find paths</button>
        </div>
      </div>
    <div id="mapid" class="jumbotron text-center"></div>

    </div>

    <script>
        $("#find_nodes").hide();
        $("#find_historic").hide();
        $("#append_nodes").hide();
        $("#road").hide();
        $("#find_roads").hide();
    </script>

    <script>
        $(document).ready( function() {
            $("#home_page").on("click", function() {
                $("#find_nodes").hide();
                $("#find_historic").hide();
                $("#append_nodes").hide();
                $("#road").hide();
                $("#find_roads").hide();


            });
            $("#find_nodes_page").on("click", function() {
                $("#find_nodes").show();
                $("#find_historic").hide();
                $("#append_nodes").hide();
                $("#road").hide();
                $("#find_roads").hide();

                window.scrollTo(0,document.body.scrollHeight);

            });
            $("#find_historic_page").on("click", function() {
                $("#find_nodes").hide();
                $("#find_historic").show();
                $("#append_nodes").hide();
                $("#road").hide();
                $("#find_roads").hide();

                window.scrollTo(0,document.body.scrollHeight);

            });
            $("#append_nodes_page").on("click", function() {
                $("#find_nodes").hide();
                $("#find_historic").hide();
                $("#append_nodes").show();
                $("#road").hide();
                $("#find_roads").hide();

                window.scrollTo(0,document.body.scrollHeight);

            });
            $("#road_page").on("click", function() {
                $("#find_nodes").hide();
                $("#find_historic").hide();
                $("#append_nodes").hide();
                $("#road").show();
                $("#find_roads").hide();

                window.scrollTo(0,document.body.scrollHeight);

            });
            $("#find_roads_page").on("click", function() {
                $("#find_nodes").hide();
                $("#find_historic").hide();
                $("#append_nodes").hide();
                $("#road").hide();
                $("#find_roads").show();

                window.scrollTo(0,document.body.scrollHeight);

            });
        });
    </script>


<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GeoApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--<link rel="stylesheet" href="https://unpkg.com/leaflet@1.0.2/dist/leaflet.css" />-->
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.0.0-rc.3/dist/leaflet.css" />
    <%= stylesheet_link_tag('leaflet-routing-machine.css') %>

    <script src="https://unpkg.com/leaflet@1.0.0-rc.3/dist/leaflet.js"></script>
    <%= javascript_include_tag('leaflet-routing-machine.js') %>
    <%= javascript_include_tag('Control.Geocoder.js') %>

    <!--<script src="https://unpkg.com/leaflet@1.0.2/dist/leaflet.js"></script>-->

  </head>

  <body>
    <%= yield :body %>
  </body>
</html>